### ISSUE TITLE
牛逼牛逼牛逼逼

### ISSUE THREAD

**Issue by mrczl** [JokingLove/site_comments#30]
https://jokinglove.com/blog/2017/09/09/others/spring-boot-helloworld/

**Comment by mrczl** [comment]
？




------------------ 原始邮件 ------------------
发件人: "JOKING"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 上午9:26
收件人: "JokingLove/site_comments"<site_comments@noreply.github.com>;
抄送: "Mrczl"<1415782655@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JokingLove/site_comments] 牛逼牛逼牛逼逼 (#30)




Closed #30.

**Comment by JokingLove** [comment]
> ？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "JOKING"<notifications@github.com>; 发送时间: 2019年7月22日(星期一) 上午9:26 收件人: "JokingLove/site_comments"<site_comments@noreply.github.com>; 抄送: "Mrczl"<1415782655@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [JokingLove/site_comments] 牛逼牛逼牛逼逼 (#30) Closed #30. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这个 issue 没按正常流程走，:smile:

**Comment by mrczl** [comment]
网站不错




------------------ 原始邮件 ------------------
发件人: "JOKING"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 上午9:40
收件人: "JokingLove/site_comments"<site_comments@noreply.github.com>;
抄送: "Mrczl"<1415782655@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JokingLove/site_comments] 牛逼牛逼牛逼逼 (#30)



 
？
 …
 ------------------ 原始邮件 ------------------ 发件人: "JOKING"notifications@github.com; 发送时间: 2019年7月22日(星期一) 上午9:26 收件人: "JokingLove/site_comments"site_comments@noreply.github.com; 抄送: "Mrczl"1415782655@qq.com;"Author"author@noreply.github.com; 主题: Re: [JokingLove/site_comments] 牛逼牛逼牛逼逼 (#30) Closed #30. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
这个 issue 没按正常流程走，😄
